# -*- coding: utf-8 -*-
"""Renewable_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3Tqq-6wBM36Ih5_PM18ovHzSKPpw1o6
"""

import pandas as pd
import numpy as np

df = pd.read_csv('Tamil_Nadu_Renewable_Energy_Forecast_2000 (1)(1).csv')

df.head()

df.describe()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

list1 =['Humidity_Pct','Pressure_mb','WindSpeed_kmh']

df[list1] = scaler.fit_transform(df[list1])

df.head()

df.drop(["Date","Time","Location"],axis=1,inplace=True)

df.head()

core = df.corr()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,10))
sns.heatmap(core,annot=True,cmap='coolwarm')
plt.show()

X = df.drop(['Solar_Energy_MW','Wind_Energy_MW','Total_Energy_MW'],axis=1)

y = df[['Solar_Energy_MW','Wind_Energy_MW','Total_Energy_MW']]

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=500,max_depth=20,random_state=42)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score
rf_accuracy = r2_score(y_test,y_pred)

rf_accuracy

from xgboost import XGBRegressor

importances = model.feature_importances_
print(importances)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

solar_model = XGBRegressor()
solar_model.fit(X_train_scaled,y_train['Solar_Energy_MW'])

wind_model = XGBRegressor()
wind_model.fit(X_train_scaled,y_train['Wind_Energy_MW'])

total_model =XGBRegressor()
total_model.fit(X_train_scaled,y_train['Total_Energy_MW'])

solar_pred = solar_model.predict(X_test_scaled)
wind_pred  = wind_model.predict(X_test_scaled)
total_pred = total_model.predict(X_test_scaled)

def evaluate_model(actual, predicted, name):
    print("\n📌 Target:", name)

    mae = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    r2 = r2_score(actual, predicted)

    print("MAE :", mae)
    print("RMSE:", rmse)
    print("R² Score:", r2)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

df.columns = df.columns.str.strip()

evaluate_model(y_test['Solar_Energy_MW'], solar_pred, "Solar Energy")
evaluate_model(y_test['Wind_Energy_MW'], wind_pred, "Wind Energy")
evaluate_model(y_test['Total_Energy_MW'], total_pred, "Total Energy")

import joblib
joblib.dump(rf_accuracy, "Tamil_Nadu_Renewable_Energy_Forecast_2000 (1)(1).pkl")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import joblib

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestRegressor())
])

pipeline.fit(X_train, y_train)

joblib.dump(pipeline, "renewable_model.pkl")

